name: key_keeper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-232.0.dev

dependencies:
  connectivity_plus: ^6.1.1
  encrypt_decrypt_plus: ^1.2.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  font_awesome_flutter: ^10.8.0
  fpdart: ^1.1.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  jiffy: ^6.3.2
  shared_preferences: ^2.3.4
  supabase_flutter: ^2.8.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true
